### Raising Errors

We've seen a variety of error messages that appear when our programs end abruptly. We can create our own errors messages too.

```python
def add_integers(*nums: int):
  """Takes an unlimited number of integers and returns their sum."""
  try:
    total = 0
    for num in nums:
      total += num
    return num
  except:
    raise Exception("Something went wrong.")  # Exception is an unspecified error

print(add_integers(3, -4, 2, 7))  # prints 12
print(add_integers("hi"))  # prints a red error message saying "Exception: Something went wrong."
```

The keyword `raise` is used to raise an error. `Exception` is the keyword for a general error, but when we raise an error we can specify what type of error happened. We can use any of [the built-in errors](https://docs.python.org/3/library/exceptions.html).

```python
def add_integers(*nums: int):
  """Takes an unlimited number of integers and returns their sum."""
  total = 0
  for num in nums:
    if type(num) != int:
      raise TypeError("The arguments must be integers.")  # TypeError is one of the a built-in errors
    total += num
  return total

print(add_integers(3, -4, 2, 7))  # prints 12
print(add_integers("hi"))  # prints a red error message saying "TypeError: The arguments must be integers."
```  

We can also create our own custom errors, which we'll do later this unit.
